/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kart;

import com.esri.core.geometry.CoordinateConversion;
import com.esri.core.geometry.Envelope;
import com.esri.core.geometry.Point;
import com.esri.core.map.Graphic;
import com.esri.core.symbol.SimpleMarkerSymbol;
import com.esri.core.symbol.TextSymbol;
import com.esri.core.tasks.na.NAFeaturesAsFeature;
import com.esri.map.ArcGISTiledMapServiceLayer;
import com.esri.map.GraphicsLayer;
import com.esri.map.JMap;
import com.esri.map.LayerList;
import com.esri.map.MapOverlay;
import com.esri.toolkit.overlays.DrawingCompleteEvent;
import com.esri.toolkit.overlays.DrawingCompleteListener;
import com.esri.toolkit.overlays.DrawingOverlay;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author Eivind Fugledal
 */
public class GUI extends javax.swing.JFrame {
    
    private JMap map;
    private GraphicsLayer graphicsLayer;
    private boolean canSetWaypoints = false;
    private int numberOfWaypoints = 0;
    private NAFeaturesAsFeature waypoints = new NAFeaturesAsFeature();
    private DrawingOverlay drawingOverlay;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        try {
            this.setWaypointsButtonActionListener();
            this.addMapToUI();
            
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MapPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        waypointsButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MapPanelLayout = new javax.swing.GroupLayout(MapPanel);
        MapPanel.setLayout(MapPanelLayout);
        MapPanelLayout.setHorizontalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        MapPanelLayout.setVerticalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        waypointsButton.setText("Set Waypoints");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waypointsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addComponent(waypointsButton)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setWaypointsButtonActionListener()
    {
        waypointsButton.addActionListener(new ActionListener() {

         public void actionPerformed(ActionEvent e) 
         {
            JToggleButton tBtn = (JToggleButton)e.getSource();
            HashMap<String, Object> attributes = new HashMap<>();
            
            if (tBtn.isSelected()) 
            {
                attributes.put("type", "Waypoints");
                drawingOverlay.setUp(DrawingOverlay.DrawingMode.POINT, new SimpleMarkerSymbol(Color.BLUE, 25, SimpleMarkerSymbol.Style.CIRCLE), attributes);
                canSetWaypoints = true;
            }
            else
            {
                canSetWaypoints = false;
            }
         }
      });
    }
    
    private JComponent addMapToUI() throws Exception
    {
        MapPanel.setLayout(new BorderLayout());
        
        map = this.createMap();
        
        MapPanel.add(map, BorderLayout.CENTER);
        
        return MapPanel;
    }
    
    private JMap createMap()
    {
        JMap jMap = new JMap();
        //jMap.addMapOverlay(new MouseClickedOverlay(jMap));
        
        // Sentrerer kartet i 62.4698, 6.2365 (Nørvasundet)
        // Sentreringen bør byttes til avlest posisjon fra GPS
        jMap.setExtent(new Envelope(new Point(6.2365, 62.4698), 0.025, 0.025));
        
        // add base layer
        ArcGISTiledMapServiceLayer tiledLayer = new ArcGISTiledMapServiceLayer("http://services.arcgisonline.com/ArcGIS/rest/services/ESRI_StreetMap_World_2D/MapServer");
        // Waypoints layer
        graphicsLayer = new GraphicsLayer();
        
        LayerList layers = jMap.getLayers();
        layers.add(tiledLayer);
        layers.add(graphicsLayer);
        
        drawingOverlay = new DrawingOverlay();
        jMap.addMapOverlay(drawingOverlay);
        drawingOverlay.setActive(true);
        drawingOverlay.addDrawingCompleteListener(new DrawingCompleteListener() 
        {
            @Override
            public void drawingCompleted(DrawingCompleteEvent arg0) 
            {
                Graphic graphic = (Graphic) drawingOverlay.getAndClearFeature();
                graphicsLayer.addGraphic(graphic);
                if (graphic.getAttributeValue("type").equals("Waypoints")) 
                {
                    if(canSetWaypoints)
                    {
                        numberOfWaypoints++;
                        waypoints.addFeature(graphic);
                        graphicsLayer.addGraphic(new Graphic(graphic.getGeometry(), new TextSymbol(12, String.valueOf(numberOfWaypoints), Color.WHITE), 1));
                    }
                    else
                    {
                        graphicsLayer.clearSelection();
                    }
                }
            }
        });

        return jMap;
    }
    
    /*private class MouseClickedOverlay extends MapOverlay
    {
        @Override
        public void onMouseClicked(MouseEvent arg0) 
        {
            try 
            {
                if (!map.isReady()) 
                {
                    return;
                }
      
                java.awt.Point screenPoint = arg0.getPoint();
                com.esri.core.geometry.Point mapPoint = map.toMapPoint(screenPoint.x, screenPoint.y);
        
                String decimalDegrees = "Decimal Degrees: " + CoordinateConversion.pointToDecimalDegrees(mapPoint, map.getSpatialReference(), 4);
        
                if(canSetWaypoints)
                {
                    System.out.println(decimalDegrees);
                }
            }  
            finally 
            {
                super.onMouseClicked(arg0);
            }
        }
    }*/
    
    /*private void setUpWaypoints()
    {
        waypointsButton.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                HashMap<String, Object> attributes = new HashMap<>();
                attributes.put("type", "Waypoints");
                drawingOverlay.setUp(DrawingOverlay.DrawingMode.POINT, new SimpleMarkerSymbol(Color.BLUE, 25, SimpleMarkerSymbol.Style.CIRCLE), attributes);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JToggleButton waypointsButton;
    // End of variables declaration//GEN-END:variables
}
